#!/bin/sh -e

. /usr/share/debconf/confmodule

[ -n "$SNOOPYDEBUG" ] && set -x

PRELOAD="/etc/ld.so.preload"
LIBNAME="/lib/snoopy.so"

# is snoopy already in $PRELOADFILE?

test -f $PRELOAD && grep "^$LIBNAME" $PRELOAD && exit 0

db_input critical snoopy/install-ld-preload || true
db_go
