#! /bin/bash
# prerm script for snoopy
# stolen from libsafe
#
# see: dh_installdeb(1)

[ -n "$SNOOPYDEBUG" ] && set -x
set -e

PRELOAD="/etc/ld.so.preload"
LIBRARY="/lib/snoopy.so"

# summary of how this script can be called:
#        * <prerm> remove'
#        * <old-prerm> upgrade' <new-version>
#        * <new-prerm> failed-upgrade' <old-version>
#        * <conflictor's-prerm> remove' in-favour' <package> <new-version>
#        * <deconfigured's-prerm> deconfigure' in-favour'
#          <package-being-installed> <version> removing'
#          <conflicting-package> <version>
# for details, see /usr/share/doc/packaging-manual/

case "$1" in
    remove|upgrade|deconfigure)
        TEMPFILE=`mktemp`
        if (grep -vqs $LIBRARY $PRELOAD) ; then
            grep -v $LIBRARY $PRELOAD > $TEMPFILE
            mv -f $TEMPFILE /etc/ld.so.preload
        else
            rm -f /etc/ld.so.preload
        fi
        rm -f $TEMPFILE
        ;;
    failed-upgrade)
        ;;
    *)
        echo >&2 "prerm called with unknown argument $1"
        exit 1
    ;;
esac

#DEBHELPER#
